# Generated by Django 5.1.2 on 2024-11-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qtext', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('op1', models.CharField(max_length=100)),
                ('op2', models.CharField(max_length=100)),
                ('op3', models.CharField(max_length=100)),
                ('op4', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
